version: '3'
services: 
  discovery:
    build: ./service-discovery/.
    ports:
      - 8761:8761
    networks:
    - production
  principal:
    build: ./service-principal/.
    ports:
      - 8080:8080
    environment: 
      - spring.profiles.active=dev
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    networks:
    - production
    depends_on: 
      - discovery
#      - mysqldoc
  auth:
    build: ./service-auth/.
    ports:
      - 8082:8082
    environment: 
      - spring.profiles.active=dev
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    networks:
    - production
    depends_on: 
      - discovery
#      - mysqldoc
  # mysqldoc:
  #   container_name: mysqlsd
  #   image: mysql
  #   environment: 
  #     MYSQL_USER: 'root'
  #     MYSQL_PASSWORD: 1234
  #     MYSQL_ROOT_PASSWORD: 1234
  #     MYSQL_DATABASE: teste
  #   ports:
  #     - "3306:3306"
  #   expose: 
  #     - 3306
  #   networks:
  #     - production
  #   volumes:
  #     - /data/database:/var/lib/mysql

networks:
  production:
    driver: bridge 